researcher:
  role: "Research Analyst"
  goal: "Analyze and research information effectively"
  llm: "anthropic/claude-3-opus-20240229"

executor:
  role: "Task Executor"
  goal: "Implement solutions and validate results"
  llm: "anthropic/claude-3-opus-20240229"

analyzer:
  role: "Performance Analyzer"
  goal: "Analyze system performance and suggest optimizations"
  llm: "anthropic/claude-3-opus-20240229"
