performance_metrics:
  response_time:
    threshold: 1000  # milliseconds
    warning_level: 800
    critical_level: 950
    
  memory_usage:
    threshold: 80  # percentage
    warning_level: 70
    critical_level: 75
    
  error_rate:
    threshold: 5  # percentage
    warning_level: 3
    critical_level: 4

optimization_rules:
  - name: "Response Time Optimization"
    condition: "response_time > warning_level"
    action: "Analyze and suggest performance improvements"
    
  - name: "Memory Usage Control"
    condition: "memory_usage > warning_level"
    action: "Identify memory leaks and optimization opportunities"
    
  - name: "Error Rate Reduction"
    condition: "error_rate > warning_level"
    action: "Review error patterns and suggest fixes"
