research_task:
  description: "Research and analyze the given topic thoroughly"
  priority: 1
  dependencies: []

execution_task:
  description: "Execute the planned solution and validate results"
  priority: 2
  dependencies: ["research_task"]

analysis_task:
  description: "Analyze performance and suggest optimizations"
  priority: 3
  dependencies: ["execution_task"]
