# NOVA Task Configuration

# Research Tasks
research_task:
  description: "Analyze and develop solution strategies using ReACT methodology"
  steps:
    - name: "Initial Analysis"
      type: "thought"
      required: true
      validation:
        - "completeness"
        - "logic"
    - name: "Knowledge Query"
      type: "action"
      required: false
      tools:
        - "symbolic_query"
        - "knowledge_search"
    - name: "Strategy Development"
      type: "thought"
      required: true
      validation:
        - "feasibility"
        - "completeness"

# Execution Tasks
execution_task:
  description: "Implement solutions with validation and error handling"
  steps:
    - name: "Plan Validation"
      type: "thought"
      required: true
      validation:
        - "prerequisites"
        - "safety"
    - name: "Tool Execution"
      type: "action"
      required: true
      tools:
        - "tool_execute"
        - "fallback_handler"
    - name: "Result Verification"
      type: "thought"
      required: true
      validation:
        - "success"
        - "completeness"

# Analysis Tasks
analysis_task:
  description: "Evaluate results and optimize performance"
  steps:
    - name: "Metric Collection"
      type: "action"
      required: true
      tools:
        - "metric_analyze"
        - "performance_track"
    - name: "Performance Analysis"
      type: "thought"
      required: true
      validation:
        - "accuracy"
        - "efficiency"
    - name: "Optimization Planning"
      type: "thought"
      required: true
      tools:
        - "optimize_suggest"

# Validation Rules
validation_rules:
  completeness:
    description: "Ensure all required components are present"
    threshold: 0.9
  
  logic:
    description: "Verify logical consistency"
    rules:
      - "no_contradictions"
      - "valid_inference"
  
  feasibility:
    description: "Check if solution is implementable"
    criteria:
      - "resource_availability"
      - "technical_feasibility"
  
  safety:
    description: "Verify safety constraints"
    checks:
      - "input_validation"
      - "error_handling"
  
  success:
    description: "Verify successful execution"
    metrics:
      - "completion_status"
      - "error_rate"
  
  accuracy:
    description: "Measure result accuracy"
    threshold: 0.95
  
  efficiency:
    description: "Evaluate performance efficiency"
    metrics:
      - "response_time"
      - "resource_usage"

# Task Processing Settings
settings:
  default_task_type: "both"
  max_retries: 3
  timeout: 300
  parallel_execution: false
  logging:
    level: "INFO"
    format: "detailed"
  metrics:
    collect: true
    store: true
    analyze: true